import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../../components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SLC Lost & Found',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        <Navbar/>
        {children}
        {/* <body className={inter.className}>{children}</body> */}
    </>
  )
}

// export default function RootLayout({children: React.ReactNode}){
//   return(
//     <>
//       <Navbar/>
//       <body className={inter.className}>{children}</body>
//     </>
//   )
// }
